/*
 * This file is generated by jOOQ.
 */
package jhi.germinate.server.database.tables.records;


import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;

import jhi.germinate.server.database.tables.ViewTableExperiments;

import org.jooq.Field;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.TableRecordImpl;


// @formatter:off
/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewTableExperimentsRecord extends TableRecordImpl<ViewTableExperimentsRecord> implements Record6<Integer, String, String, Date, String, Timestamp> {

    private static final long serialVersionUID = 19267866;

    /**
     * Setter for <code>germinate_template_4_0_0.view_table_experiments.experiment_id</code>. Primary id for this table. This uniquely identifies the row.
     */
    public void setExperimentId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>germinate_template_4_0_0.view_table_experiments.experiment_id</code>. Primary id for this table. This uniquely identifies the row.
     */
    public Integer getExperimentId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>germinate_template_4_0_0.view_table_experiments.experiment_name</code>. The name of the experiment.
     */
    public void setExperimentName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>germinate_template_4_0_0.view_table_experiments.experiment_name</code>. The name of the experiment.
     */
    public String getExperimentName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>germinate_template_4_0_0.view_table_experiments.experiment_description</code>. Describes the experiment.
     */
    public void setExperimentDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>germinate_template_4_0_0.view_table_experiments.experiment_description</code>. Describes the experiment.
     */
    public String getExperimentDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>germinate_template_4_0_0.view_table_experiments.experiment_date</code>. The date that the experiment was carried out.
     */
    public void setExperimentDate(Date value) {
        set(3, value);
    }

    /**
     * Getter for <code>germinate_template_4_0_0.view_table_experiments.experiment_date</code>. The date that the experiment was carried out.
     */
    public Date getExperimentDate() {
        return (Date) get(3);
    }

    /**
     * Setter for <code>germinate_template_4_0_0.view_table_experiments.experimenttype_description</code>. Describes the experiment type.
     */
    public void setExperimenttypeDescription(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>germinate_template_4_0_0.view_table_experiments.experimenttype_description</code>. Describes the experiment type.
     */
    public String getExperimenttypeDescription() {
        return (String) get(4);
    }

    /**
     * Setter for <code>germinate_template_4_0_0.view_table_experiments.created_on</code>. When the record was created.
     */
    public void setCreatedOn(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>germinate_template_4_0_0.view_table_experiments.created_on</code>. When the record was created.
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) get(5);
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, Date, String, Timestamp> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, Date, String, Timestamp> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return ViewTableExperiments.VIEW_TABLE_EXPERIMENTS.EXPERIMENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ViewTableExperiments.VIEW_TABLE_EXPERIMENTS.EXPERIMENT_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return ViewTableExperiments.VIEW_TABLE_EXPERIMENTS.EXPERIMENT_DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field4() {
        return ViewTableExperiments.VIEW_TABLE_EXPERIMENTS.EXPERIMENT_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return ViewTableExperiments.VIEW_TABLE_EXPERIMENTS.EXPERIMENTTYPE_DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return ViewTableExperiments.VIEW_TABLE_EXPERIMENTS.CREATED_ON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getExperimentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getExperimentName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getExperimentDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component4() {
        return getExperimentDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getExperimenttypeDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getExperimentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getExperimentName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getExperimentDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value4() {
        return getExperimentDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getExperimenttypeDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewTableExperimentsRecord value1(Integer value) {
        setExperimentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewTableExperimentsRecord value2(String value) {
        setExperimentName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewTableExperimentsRecord value3(String value) {
        setExperimentDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewTableExperimentsRecord value4(Date value) {
        setExperimentDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewTableExperimentsRecord value5(String value) {
        setExperimenttypeDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewTableExperimentsRecord value6(Timestamp value) {
        setCreatedOn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewTableExperimentsRecord values(Integer value1, String value2, String value3, Date value4, String value5, Timestamp value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ViewTableExperimentsRecord
     */
    public ViewTableExperimentsRecord() {
        super(ViewTableExperiments.VIEW_TABLE_EXPERIMENTS);
    }

    /**
     * Create a detached, initialised ViewTableExperimentsRecord
     */
    public ViewTableExperimentsRecord(Integer experimentId, String experimentName, String experimentDescription, Date experimentDate, String experimenttypeDescription, Timestamp createdOn) {
        super(ViewTableExperiments.VIEW_TABLE_EXPERIMENTS);

        set(0, experimentId);
        set(1, experimentName);
        set(2, experimentDescription);
        set(3, experimentDate);
        set(4, experimenttypeDescription);
        set(5, createdOn);
    }
// @formatter:on
}
