/*
 * This file is generated by jOOQ.
 */
package jhi.germinate.server.database.tables.records;


import com.google.gson.JsonArray;

import javax.annotation.Generated;

import jhi.germinate.server.database.tables.ViewTableCompounds;

import org.jooq.Field;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.TableRecordImpl;


// @formatter:off
/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewTableCompoundsRecord extends TableRecordImpl<ViewTableCompoundsRecord> implements Record9<Integer, String, String, Integer, String, String, String, JsonArray, Long> {

    private static final long serialVersionUID = -369397;

    /**
     * Setter for <code>germinate_template_3_7_0.view_table_compounds.compound_id</code>. Primary id for this table. This uniquely identifies the row.
     */
    public void setCompoundId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>germinate_template_3_7_0.view_table_compounds.compound_id</code>. Primary id for this table. This uniquely identifies the row.
     */
    public Integer getCompoundId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>germinate_template_3_7_0.view_table_compounds.compound_name</code>. Compound full name.
     */
    public void setCompoundName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>germinate_template_3_7_0.view_table_compounds.compound_name</code>. Compound full name.
     */
    public String getCompoundName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>germinate_template_3_7_0.view_table_compounds.compound_description</code>. Full description of the compound. This should contain enough infomation to accurately identify the compound and how it was recorded.
     */
    public void setCompoundDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>germinate_template_3_7_0.view_table_compounds.compound_description</code>. Full description of the compound. This should contain enough infomation to accurately identify the compound and how it was recorded.
     */
    public String getCompoundDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>germinate_template_3_7_0.view_table_compounds.unit_id</code>. Primary id for this table. This uniquely identifies the row.
     */
    public void setUnitId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>germinate_template_3_7_0.view_table_compounds.unit_id</code>. Primary id for this table. This uniquely identifies the row.
     */
    public Integer getUnitId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>germinate_template_3_7_0.view_table_compounds.unit_name</code>. The name of the unit. This should be the name of the unit in full.
     */
    public void setUnitName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>germinate_template_3_7_0.view_table_compounds.unit_name</code>. The name of the unit. This should be the name of the unit in full.
     */
    public String getUnitName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>germinate_template_3_7_0.view_table_compounds.unit_description</code>. A description of the unit. If the unit is not a standard SI unit then it is beneficial to have a description which explains what the unit it, how it is derived and any other information which would help identifiy it.
     */
    public void setUnitDescription(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>germinate_template_3_7_0.view_table_compounds.unit_description</code>. A description of the unit. If the unit is not a standard SI unit then it is beneficial to have a description which explains what the unit it, how it is derived and any other information which would help identifiy it.
     */
    public String getUnitDescription() {
        return (String) get(5);
    }

    /**
     * Setter for <code>germinate_template_3_7_0.view_table_compounds.unit_abbreviation</code>. This should be the unit abbreviation.
     */
    public void setUnitAbbreviation(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>germinate_template_3_7_0.view_table_compounds.unit_abbreviation</code>. This should be the unit abbreviation.
     */
    public String getUnitAbbreviation() {
        return (String) get(6);
    }

    /**
     * Setter for <code>germinate_template_3_7_0.view_table_compounds.synonyms</code>. The synonyms as a json array.
     */
    public void setSynonyms(JsonArray value) {
        set(7, value);
    }

    /**
     * Getter for <code>germinate_template_3_7_0.view_table_compounds.synonyms</code>. The synonyms as a json array.
     */
    public JsonArray getSynonyms() {
        return (JsonArray) get(7);
    }

    /**
     * Setter for <code>germinate_template_3_7_0.view_table_compounds.count</code>.
     */
    public void setCount(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>germinate_template_3_7_0.view_table_compounds.count</code>.
     */
    public Long getCount() {
        return (Long) get(8);
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, String, Integer, String, String, String, JsonArray, Long> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, String, Integer, String, String, String, JsonArray, Long> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return ViewTableCompounds.VIEW_TABLE_COMPOUNDS.COMPOUND_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ViewTableCompounds.VIEW_TABLE_COMPOUNDS.COMPOUND_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return ViewTableCompounds.VIEW_TABLE_COMPOUNDS.COMPOUND_DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return ViewTableCompounds.VIEW_TABLE_COMPOUNDS.UNIT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return ViewTableCompounds.VIEW_TABLE_COMPOUNDS.UNIT_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return ViewTableCompounds.VIEW_TABLE_COMPOUNDS.UNIT_DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return ViewTableCompounds.VIEW_TABLE_COMPOUNDS.UNIT_ABBREVIATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<JsonArray> field8() {
        return ViewTableCompounds.VIEW_TABLE_COMPOUNDS.SYNONYMS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field9() {
        return ViewTableCompounds.VIEW_TABLE_COMPOUNDS.COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getCompoundId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getCompoundName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getCompoundDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getUnitId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getUnitName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getUnitDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getUnitAbbreviation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JsonArray component8() {
        return getSynonyms();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component9() {
        return getCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getCompoundId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCompoundName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCompoundDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getUnitId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getUnitName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getUnitDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getUnitAbbreviation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JsonArray value8() {
        return getSynonyms();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value9() {
        return getCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewTableCompoundsRecord value1(Integer value) {
        setCompoundId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewTableCompoundsRecord value2(String value) {
        setCompoundName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewTableCompoundsRecord value3(String value) {
        setCompoundDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewTableCompoundsRecord value4(Integer value) {
        setUnitId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewTableCompoundsRecord value5(String value) {
        setUnitName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewTableCompoundsRecord value6(String value) {
        setUnitDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewTableCompoundsRecord value7(String value) {
        setUnitAbbreviation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewTableCompoundsRecord value8(JsonArray value) {
        setSynonyms(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewTableCompoundsRecord value9(Long value) {
        setCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewTableCompoundsRecord values(Integer value1, String value2, String value3, Integer value4, String value5, String value6, String value7, JsonArray value8, Long value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ViewTableCompoundsRecord
     */
    public ViewTableCompoundsRecord() {
        super(ViewTableCompounds.VIEW_TABLE_COMPOUNDS);
    }

    /**
     * Create a detached, initialised ViewTableCompoundsRecord
     */
    public ViewTableCompoundsRecord(Integer compoundId, String compoundName, String compoundDescription, Integer unitId, String unitName, String unitDescription, String unitAbbreviation, JsonArray synonyms, Long count) {
        super(ViewTableCompounds.VIEW_TABLE_COMPOUNDS);

        set(0, compoundId);
        set(1, compoundName);
        set(2, compoundDescription);
        set(3, unitId);
        set(4, unitName);
        set(5, unitDescription);
        set(6, unitAbbreviation);
        set(7, synonyms);
        set(8, count);
    }
// @formatter:on
}
