/*
 * This file is generated by jOOQ.
 */
package jhi.germinate.server.database.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import jhi.germinate.server.database.tables.ViewTableImages;

import org.jooq.Field;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.TableRecordImpl;


// @formatter:off
/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewTableImagesRecord extends TableRecordImpl<ViewTableImagesRecord> implements Record8<Integer, String, Integer, String, String, String, String, Timestamp> {

    private static final long serialVersionUID = 1997994654;

    /**
     * Setter for <code>germinate_template_4_0_0.view_table_images.image_id</code>.
     */
    public void setImageId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>germinate_template_4_0_0.view_table_images.image_id</code>.
     */
    public Integer getImageId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>germinate_template_4_0_0.view_table_images.image_description</code>.
     */
    public void setImageDescription(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>germinate_template_4_0_0.view_table_images.image_description</code>.
     */
    public String getImageDescription() {
        return (String) get(1);
    }

    /**
     * Setter for <code>germinate_template_4_0_0.view_table_images.image_foreign_id</code>.
     */
    public void setImageForeignId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>germinate_template_4_0_0.view_table_images.image_foreign_id</code>.
     */
    public Integer getImageForeignId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>germinate_template_4_0_0.view_table_images.image_path</code>.
     */
    public void setImagePath(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>germinate_template_4_0_0.view_table_images.image_path</code>.
     */
    public String getImagePath() {
        return (String) get(3);
    }

    /**
     * Setter for <code>germinate_template_4_0_0.view_table_images.image_type</code>.
     */
    public void setImageType(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>germinate_template_4_0_0.view_table_images.image_type</code>.
     */
    public String getImageType() {
        return (String) get(4);
    }

    /**
     * Setter for <code>germinate_template_4_0_0.view_table_images.image_ref_table</code>.
     */
    public void setImageRefTable(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>germinate_template_4_0_0.view_table_images.image_ref_table</code>.
     */
    public String getImageRefTable() {
        return (String) get(5);
    }

    /**
     * Setter for <code>germinate_template_4_0_0.view_table_images.reference_name</code>.
     */
    public void setReferenceName(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>germinate_template_4_0_0.view_table_images.reference_name</code>.
     */
    public String getReferenceName() {
        return (String) get(6);
    }

    /**
     * Setter for <code>germinate_template_4_0_0.view_table_images.created_on</code>.
     */
    public void setCreatedOn(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>germinate_template_4_0_0.view_table_images.created_on</code>.
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) get(7);
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, Integer, String, String, String, String, Timestamp> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, Integer, String, String, String, String, Timestamp> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return ViewTableImages.VIEW_TABLE_IMAGES.IMAGE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ViewTableImages.VIEW_TABLE_IMAGES.IMAGE_DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return ViewTableImages.VIEW_TABLE_IMAGES.IMAGE_FOREIGN_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return ViewTableImages.VIEW_TABLE_IMAGES.IMAGE_PATH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return ViewTableImages.VIEW_TABLE_IMAGES.IMAGE_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return ViewTableImages.VIEW_TABLE_IMAGES.IMAGE_REF_TABLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return ViewTableImages.VIEW_TABLE_IMAGES.REFERENCE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return ViewTableImages.VIEW_TABLE_IMAGES.CREATED_ON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getImageId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getImageDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getImageForeignId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getImagePath();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getImageType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getImageRefTable();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getReferenceName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getImageId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getImageDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getImageForeignId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getImagePath();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getImageType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getImageRefTable();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getReferenceName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewTableImagesRecord value1(Integer value) {
        setImageId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewTableImagesRecord value2(String value) {
        setImageDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewTableImagesRecord value3(Integer value) {
        setImageForeignId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewTableImagesRecord value4(String value) {
        setImagePath(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewTableImagesRecord value5(String value) {
        setImageType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewTableImagesRecord value6(String value) {
        setImageRefTable(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewTableImagesRecord value7(String value) {
        setReferenceName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewTableImagesRecord value8(Timestamp value) {
        setCreatedOn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewTableImagesRecord values(Integer value1, String value2, Integer value3, String value4, String value5, String value6, String value7, Timestamp value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ViewTableImagesRecord
     */
    public ViewTableImagesRecord() {
        super(ViewTableImages.VIEW_TABLE_IMAGES);
    }

    /**
     * Create a detached, initialised ViewTableImagesRecord
     */
    public ViewTableImagesRecord(Integer imageId, String imageDescription, Integer imageForeignId, String imagePath, String imageType, String imageRefTable, String referenceName, Timestamp createdOn) {
        super(ViewTableImages.VIEW_TABLE_IMAGES);

        set(0, imageId);
        set(1, imageDescription);
        set(2, imageForeignId);
        set(3, imagePath);
        set(4, imageType);
        set(5, imageRefTable);
        set(6, referenceName);
        set(7, createdOn);
    }
// @formatter:on
}
