/*
 * This file is generated by jOOQ.
 */
package jhi.germinate.server.database.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


// @formatter:off
/**
 * Defines institutions within Germinate. Accessions may be associated with 
 * an institute and this can be defined here.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Institutions implements Serializable {

    private static final long serialVersionUID = -239741109;

    private Integer   id;
    private String    code;
    private String    name;
    private String    acronym;
    private Integer   countryId;
    private String    contact;
    private String    phone;
    private String    email;
    private String    address;
    private Timestamp createdOn;
    private Timestamp updatedOn;

    public Institutions() {}

    public Institutions(Institutions value) {
        this.id = value.id;
        this.code = value.code;
        this.name = value.name;
        this.acronym = value.acronym;
        this.countryId = value.countryId;
        this.contact = value.contact;
        this.phone = value.phone;
        this.email = value.email;
        this.address = value.address;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
    }

    public Institutions(
        Integer   id,
        String    code,
        String    name,
        String    acronym,
        Integer   countryId,
        String    contact,
        String    phone,
        String    email,
        String    address,
        Timestamp createdOn,
        Timestamp updatedOn
    ) {
        this.id = id;
        this.code = code;
        this.name = name;
        this.acronym = acronym;
        this.countryId = countryId;
        this.contact = contact;
        this.phone = phone;
        this.email = email;
        this.address = address;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAcronym() {
        return this.acronym;
    }

    public void setAcronym(String acronym) {
        this.acronym = acronym;
    }

    public Integer getCountryId() {
        return this.countryId;
    }

    public void setCountryId(Integer countryId) {
        this.countryId = countryId;
    }

    public String getContact() {
        return this.contact;
    }

    public void setContact(String contact) {
        this.contact = contact;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public Timestamp getCreatedOn() {
        return this.createdOn;
    }

    public void setCreatedOn(Timestamp createdOn) {
        this.createdOn = createdOn;
    }

    public Timestamp getUpdatedOn() {
        return this.updatedOn;
    }

    public void setUpdatedOn(Timestamp updatedOn) {
        this.updatedOn = updatedOn;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Institutions (");

        sb.append(id);
        sb.append(", ").append(code);
        sb.append(", ").append(name);
        sb.append(", ").append(acronym);
        sb.append(", ").append(countryId);
        sb.append(", ").append(contact);
        sb.append(", ").append(phone);
        sb.append(", ").append(email);
        sb.append(", ").append(address);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);

        sb.append(")");
        return sb.toString();
    }
// @formatter:on
}
