/*
 * This file is generated by jOOQ.
 */
package jhi.germinate.server.database.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


// @formatter:off
/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewStatsOverview implements Serializable {

    private static final long serialVersionUID = 944058436;

    private Long germplasm;
    private Long markers;
    private Long traits;
    private Long compounds;
    private Long locations;
    private Long groups;
    private Long images;

    public ViewStatsOverview() {}

    public ViewStatsOverview(ViewStatsOverview value) {
        this.germplasm = value.germplasm;
        this.markers = value.markers;
        this.traits = value.traits;
        this.compounds = value.compounds;
        this.locations = value.locations;
        this.groups = value.groups;
        this.images = value.images;
    }

    public ViewStatsOverview(
        Long germplasm,
        Long markers,
        Long traits,
        Long compounds,
        Long locations,
        Long groups,
        Long images
    ) {
        this.germplasm = germplasm;
        this.markers = markers;
        this.traits = traits;
        this.compounds = compounds;
        this.locations = locations;
        this.groups = groups;
        this.images = images;
    }

    public Long getGermplasm() {
        return this.germplasm;
    }

    public void setGermplasm(Long germplasm) {
        this.germplasm = germplasm;
    }

    public Long getMarkers() {
        return this.markers;
    }

    public void setMarkers(Long markers) {
        this.markers = markers;
    }

    public Long getTraits() {
        return this.traits;
    }

    public void setTraits(Long traits) {
        this.traits = traits;
    }

    public Long getCompounds() {
        return this.compounds;
    }

    public void setCompounds(Long compounds) {
        this.compounds = compounds;
    }

    public Long getLocations() {
        return this.locations;
    }

    public void setLocations(Long locations) {
        this.locations = locations;
    }

    public Long getGroups() {
        return this.groups;
    }

    public void setGroups(Long groups) {
        this.groups = groups;
    }

    public Long getImages() {
        return this.images;
    }

    public void setImages(Long images) {
        this.images = images;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ViewStatsOverview (");

        sb.append(germplasm);
        sb.append(", ").append(markers);
        sb.append(", ").append(traits);
        sb.append(", ").append(compounds);
        sb.append(", ").append(locations);
        sb.append(", ").append(groups);
        sb.append(", ").append(images);

        sb.append(")");
        return sb.toString();
    }
// @formatter:on
}
