/*
 * This file is generated by jOOQ.
 */
package jhi.germinate.server.database.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import jhi.germinate.server.database.tables.ViewTableGroups;

import org.jooq.Field;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.TableRecordImpl;


// @formatter:off
/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewTableGroupsRecord extends TableRecordImpl<ViewTableGroupsRecord> implements Record10<Integer, String, String, Integer, String, Integer, Boolean, Timestamp, Timestamp, Long> {

    private static final long serialVersionUID = -1861750135;

    /**
     * Create a detached ViewTableGroupsRecord
     */
    public ViewTableGroupsRecord() {
        super(ViewTableGroups.VIEW_TABLE_GROUPS);
    }

    /**
     * Getter for <code>germinate_template_3_7_0.view_table_groups.group_id</code>. Primary id for this table. This uniquely identifies the row.
     */
    public Integer getGroupId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>germinate_template_3_7_0.view_table_groups.group_name</code>. The name of the group which can be used to identify it.
     */
    public void setGroupName(String value) {
        set(1, value);
    }

    /**
     * Create a detached, initialised ViewTableGroupsRecord
     */
    public ViewTableGroupsRecord(Integer groupId, String groupName, String groupDescription, Integer groupTypeId, String groupType, Integer userId, Boolean groupVisibility, Timestamp createdOn, Timestamp updatedOn, Long count) {
        super(ViewTableGroups.VIEW_TABLE_GROUPS);

        set(0, groupId);
        set(1, groupName);
        set(2, groupDescription);
        set(3, groupTypeId);
        set(4, groupType);
        set(5, userId);
        set(6, groupVisibility);
        set(7, createdOn);
        set(8, updatedOn);
        set(9, count);
    }

    /**
     * Setter for <code>germinate_template_3_7_0.view_table_groups.group_description</code>. A free text description of the group. This has no length limitations.
     */
    public void setGroupDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>germinate_template_3_7_0.view_table_groups.group_description</code>. A free text description of the group. This has no length limitations.
     */
    public String getGroupDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>germinate_template_3_7_0.view_table_groups.group_type_id</code>.
     */
    public void setGroupTypeId(Integer value) {
        set(3, value);
    }

    /**
     * Setter for <code>germinate_template_3_7_0.view_table_groups.group_id</code>. Primary id for this table. This uniquely identifies the row.
     */
    public void setGroupId(Integer value) {
        set(0, value);
    }

    /**
     * Setter for <code>germinate_template_3_7_0.view_table_groups.group_type</code>.
     */
    public void setGroupType(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>germinate_template_3_7_0.view_table_groups.group_type</code>.
     */
    public String getGroupType() {
        return (String) get(4);
    }

    /**
     * Setter for <code>germinate_template_3_7_0.view_table_groups.user_id</code>. Defines who created the group. Foreign key to Gatekeeper users (Gatekeeper users.id).
     */
    public void setUserId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>germinate_template_3_7_0.view_table_groups.user_id</code>. Defines who created the group. Foreign key to Gatekeeper users (Gatekeeper users.id).
     */
    public Integer getUserId() {
        return (Integer) get(5);
    }

    /**
     * Getter for <code>germinate_template_3_7_0.view_table_groups.group_name</code>. The name of the group which can be used to identify it.
     */
    public String getGroupName() {
        return (String) get(1);
    }

    /**
     * Getter for <code>germinate_template_3_7_0.view_table_groups.group_visibility</code>. Defines if the group is visuble or hidden from the Germinate user interface.
     */
    public Boolean getGroupVisibility() {
        return (Boolean) get(6);
    }

    /**
     * Getter for <code>germinate_template_3_7_0.view_table_groups.group_type_id</code>.
     */
    public Integer getGroupTypeId() {
        return (Integer) get(3);
    }

    /**
     * Getter for <code>germinate_template_3_7_0.view_table_groups.created_on</code>. Foreign key to locations (locations.id).
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>germinate_template_3_7_0.view_table_groups.group_visibility</code>. Defines if the group is visuble or hidden from the Germinate user interface.
     */
    public void setGroupVisibility(Boolean value) {
        set(6, value);
    }

    /**
     * Setter for <code>germinate_template_3_7_0.view_table_groups.created_on</code>. Foreign key to locations (locations.id).
     */
    public void setCreatedOn(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>germinate_template_3_7_0.view_table_groups.updated_on</code>. When the record was updated. This may be different from the created on date if subsequent changes have been made to the underlying record.
     */
    public Timestamp getUpdatedOn() {
        return (Timestamp) get(8);
    }

    /**
     * Getter for <code>germinate_template_3_7_0.view_table_groups.count</code>.
     */
    public Long getCount() {
        return (Long) get(9);
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, String, Integer, String, Integer, Boolean, Timestamp, Timestamp, Long> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, String, Integer, String, Integer, Boolean, Timestamp, Timestamp, Long> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return ViewTableGroups.VIEW_TABLE_GROUPS.GROUP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ViewTableGroups.VIEW_TABLE_GROUPS.GROUP_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return ViewTableGroups.VIEW_TABLE_GROUPS.GROUP_DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return ViewTableGroups.VIEW_TABLE_GROUPS.GROUP_TYPE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return ViewTableGroups.VIEW_TABLE_GROUPS.GROUP_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return ViewTableGroups.VIEW_TABLE_GROUPS.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field7() {
        return ViewTableGroups.VIEW_TABLE_GROUPS.GROUP_VISIBILITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return ViewTableGroups.VIEW_TABLE_GROUPS.CREATED_ON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return ViewTableGroups.VIEW_TABLE_GROUPS.UPDATED_ON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field10() {
        return ViewTableGroups.VIEW_TABLE_GROUPS.COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getGroupId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getGroupName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getGroupDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getGroupTypeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getGroupType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component7() {
        return getGroupVisibility();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getUpdatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component10() {
        return getCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getGroupId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getGroupName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getGroupDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getGroupTypeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getGroupType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value7() {
        return getGroupVisibility();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getUpdatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value10() {
        return getCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewTableGroupsRecord value1(Integer value) {
        setGroupId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewTableGroupsRecord value2(String value) {
        setGroupName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewTableGroupsRecord value3(String value) {
        setGroupDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewTableGroupsRecord value4(Integer value) {
        setGroupTypeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewTableGroupsRecord value5(String value) {
        setGroupType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewTableGroupsRecord value6(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewTableGroupsRecord value7(Boolean value) {
        setGroupVisibility(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewTableGroupsRecord value8(Timestamp value) {
        setCreatedOn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewTableGroupsRecord value9(Timestamp value) {
        setUpdatedOn(value);
        return this;
    }

    /**
     * Setter for <code>germinate_template_3_7_0.view_table_groups.updated_on</code>. When the record was updated. This may be different from the created on date if subsequent changes have been made to the underlying record.
     */
    public void setUpdatedOn(Timestamp value) {
        set(8, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewTableGroupsRecord values(Integer value1, String value2, String value3, Integer value4, String value5, Integer value6, Boolean value7, Timestamp value8, Timestamp value9, Long value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>germinate_template_3_7_0.view_table_groups.count</code>.
     */
    public void setCount(Long value) {
        set(9, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewTableGroupsRecord value10(Long value) {
        setCount(value);
        return this;
    }
// @formatter:on
}
