/*
 * This file is generated by jOOQ.
 */
package jhi.germinate.server.database.tables.records;


import com.google.gson.JsonArray;

import javax.annotation.Generated;

import jhi.germinate.server.database.tables.ViewTableMapdefinitions;

import org.jooq.Field;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.TableRecordImpl;


// @formatter:off
/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewTableMapdefinitionsRecord extends TableRecordImpl<ViewTableMapdefinitionsRecord> implements Record10<Integer, String, JsonArray, String, Integer, Integer, Boolean, String, String, Double> {

    private static final long serialVersionUID = 178161496;

    /**
     * Create a detached ViewTableMapdefinitionsRecord
     */
    public ViewTableMapdefinitionsRecord() {
        super(ViewTableMapdefinitions.VIEW_TABLE_MAPDEFINITIONS);
    }

    /**
     * Create a detached, initialised ViewTableMapdefinitionsRecord
     */
    public ViewTableMapdefinitionsRecord(Integer markerId, String markerName, JsonArray synonyms, String mapFeatureType, Integer mapId, Integer userId, Boolean visibility, String mapMame, String chromosome, Double position) {
        super(ViewTableMapdefinitions.VIEW_TABLE_MAPDEFINITIONS);

        set(0, markerId);
        set(1, markerName);
        set(2, synonyms);
        set(3, mapFeatureType);
        set(4, mapId);
        set(5, userId);
        set(6, visibility);
        set(7, mapMame);
        set(8, chromosome);
        set(9, position);
    }

    /**
     * Getter for <code>germinate_template_3_7_0.view_table_mapdefinitions.marker_id</code>. Primary id for this table. This uniquely identifies the row.
     */
    public Integer getMarkerId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>germinate_template_3_7_0.view_table_mapdefinitions.marker_id</code>. Primary id for this table. This uniquely identifies the row.
     */
    public void setMarkerId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>germinate_template_3_7_0.view_table_mapdefinitions.marker_name</code>. The name of the marker. This should be a unique name which identifies the marker.
     */
    public String getMarkerName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>germinate_template_3_7_0.view_table_mapdefinitions.marker_name</code>. The name of the marker. This should be a unique name which identifies the marker.
     */
    public void setMarkerName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>germinate_template_3_7_0.view_table_mapdefinitions.synonyms</code>. The synonyms as a json array.
     */
    public JsonArray getSynonyms() {
        return (JsonArray) get(2);
    }

    /**
     * Setter for <code>germinate_template_3_7_0.view_table_mapdefinitions.synonyms</code>. The synonyms as a json array.
     */
    public void setSynonyms(JsonArray value) {
        set(2, value);
    }

    /**
     * Getter for <code>germinate_template_3_7_0.view_table_mapdefinitions.map_feature_type</code>. Description of the feature type. This could include a definition of the marker type such as 'SNP', 'KASP' or 'AFLP'.
     */
    public String getMapFeatureType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>germinate_template_3_7_0.view_table_mapdefinitions.map_feature_type</code>. Description of the feature type. This could include a definition of the marker type such as 'SNP', 'KASP' or 'AFLP'.
     */
    public void setMapFeatureType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>germinate_template_3_7_0.view_table_mapdefinitions.map_id</code>. Primary id for this table. This uniquely identifies the row.
     */
    public Integer getMapId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>germinate_template_3_7_0.view_table_mapdefinitions.map_id</code>. Primary id for this table. This uniquely identifies the row.
     */
    public void setMapId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>germinate_template_3_7_0.view_table_mapdefinitions.user_id</code>. Foreign key to Gatekeeper users (Gatekeeper users.id).
     */
    public Integer getUserId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>germinate_template_3_7_0.view_table_mapdefinitions.user_id</code>. Foreign key to Gatekeeper users (Gatekeeper users.id).
     */
    public void setUserId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>germinate_template_3_7_0.view_table_mapdefinitions.visibility</code>. Determines if the map is visible to the Germinate interface or hidden.
     */
    public Boolean getVisibility() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>germinate_template_3_7_0.view_table_mapdefinitions.visibility</code>. Determines if the map is visible to the Germinate interface or hidden.
     */
    public void setVisibility(Boolean value) {
        set(6, value);
    }

    /**
     * Setter for <code>germinate_template_3_7_0.view_table_mapdefinitions.chromosome</code>. The chromosome/linkage group that this marker is found on.
     */
    public void setChromosome(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>germinate_template_3_7_0.view_table_mapdefinitions.chromosome</code>. The chromosome/linkage group that this marker is found on.
     */
    public String getChromosome() {
        return (String) get(8);
    }

    /**
     * Getter for <code>germinate_template_3_7_0.view_table_mapdefinitions.map_mame</code>. Describes the map.
     */
    public String getMapMame() {
        return (String) get(7);
    }

    /**
     * Setter for <code>germinate_template_3_7_0.view_table_mapdefinitions.map_mame</code>. Describes the map.
     */
    public void setMapMame(String value) {
        set(7, value);
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>germinate_template_3_7_0.view_table_mapdefinitions.position</code>. Used if the markers location spans over an area more than a single point on the maps. Determines the marker start location.
     */
    public Double getPosition() {
        return (Double) get(9);
    }

    /**
     * Setter for <code>germinate_template_3_7_0.view_table_mapdefinitions.position</code>. Used if the markers location spans over an area more than a single point on the maps. Determines the marker start location.
     */
    public void setPosition(Double value) {
        set(9, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, JsonArray, String, Integer, Integer, Boolean, String, String, Double> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, JsonArray, String, Integer, Integer, Boolean, String, String, Double> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return ViewTableMapdefinitions.VIEW_TABLE_MAPDEFINITIONS.MARKER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ViewTableMapdefinitions.VIEW_TABLE_MAPDEFINITIONS.MARKER_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<JsonArray> field3() {
        return ViewTableMapdefinitions.VIEW_TABLE_MAPDEFINITIONS.SYNONYMS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return ViewTableMapdefinitions.VIEW_TABLE_MAPDEFINITIONS.MAP_FEATURE_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return ViewTableMapdefinitions.VIEW_TABLE_MAPDEFINITIONS.MAP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return ViewTableMapdefinitions.VIEW_TABLE_MAPDEFINITIONS.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return ViewTableMapdefinitions.VIEW_TABLE_MAPDEFINITIONS.CHROMOSOME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field10() {
        return ViewTableMapdefinitions.VIEW_TABLE_MAPDEFINITIONS.POSITION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field7() {
        return ViewTableMapdefinitions.VIEW_TABLE_MAPDEFINITIONS.VISIBILITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return ViewTableMapdefinitions.VIEW_TABLE_MAPDEFINITIONS.MAP_MAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getMarkerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getMarkerName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JsonArray component3() {
        return getSynonyms();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getMapFeatureType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getMapId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getChromosome();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component10() {
        return getPosition();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component7() {
        return getVisibility();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getMapMame();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getMarkerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getMarkerName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JsonArray value3() {
        return getSynonyms();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getMapFeatureType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getMapId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getChromosome();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value10() {
        return getPosition();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value7() {
        return getVisibility();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getMapMame();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewTableMapdefinitionsRecord value1(Integer value) {
        setMarkerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewTableMapdefinitionsRecord value2(String value) {
        setMarkerName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewTableMapdefinitionsRecord value3(JsonArray value) {
        setSynonyms(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewTableMapdefinitionsRecord value4(String value) {
        setMapFeatureType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewTableMapdefinitionsRecord value5(Integer value) {
        setMapId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewTableMapdefinitionsRecord value6(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewTableMapdefinitionsRecord value9(String value) {
        setChromosome(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewTableMapdefinitionsRecord value10(Double value) {
        setPosition(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewTableMapdefinitionsRecord value7(Boolean value) {
        setVisibility(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewTableMapdefinitionsRecord value8(String value) {
        setMapMame(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewTableMapdefinitionsRecord values(Integer value1, String value2, JsonArray value3, String value4, Integer value5, Integer value6, Boolean value7, String value8, String value9, Double value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }
// @formatter:on
}
