/*
 * This file is generated by jOOQ.
 */
package jhi.germinate.server.database.tables.records;


import javax.annotation.Generated;

import jhi.germinate.server.database.tables.ViewTableMaps;

import org.jooq.Field;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.TableRecordImpl;


// @formatter:off
/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewTableMapsRecord extends TableRecordImpl<ViewTableMapsRecord> implements Record6<Integer, String, String, Integer, Boolean, Long> {

    private static final long serialVersionUID = -1397422863;

    /**
     * Create a detached ViewTableMapsRecord
     */
    public ViewTableMapsRecord() {
        super(ViewTableMaps.VIEW_TABLE_MAPS);
    }

    /**
     * Create a detached, initialised ViewTableMapsRecord
     */
    public ViewTableMapsRecord(Integer mapId, String mapName, String mapDescription, Integer userId, Boolean visibility, Long markerCount) {
        super(ViewTableMaps.VIEW_TABLE_MAPS);

        set(0, mapId);
        set(1, mapName);
        set(2, mapDescription);
        set(3, userId);
        set(4, visibility);
        set(5, markerCount);
    }

    /**
     * Getter for <code>germinate_template_3_7_0.view_table_maps.map_id</code>. Primary id for this table. This uniquely identifies the row.
     */
    public Integer getMapId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>germinate_template_3_7_0.view_table_maps.map_id</code>. Primary id for this table. This uniquely identifies the row.
     */
    public void setMapId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>germinate_template_3_7_0.view_table_maps.map_name</code>. Describes the map.
     */
    public String getMapName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>germinate_template_3_7_0.view_table_maps.map_name</code>. Describes the map.
     */
    public void setMapName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>germinate_template_3_7_0.view_table_maps.map_description</code>. The name of this map.
     */
    public String getMapDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>germinate_template_3_7_0.view_table_maps.map_description</code>. The name of this map.
     */
    public void setMapDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>germinate_template_3_7_0.view_table_maps.user_id</code>. Foreign key to Gatekeeper users (Gatekeeper users.id).
     */
    public Integer getUserId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>germinate_template_3_7_0.view_table_maps.user_id</code>. Foreign key to Gatekeeper users (Gatekeeper users.id).
     */
    public void setUserId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>germinate_template_3_7_0.view_table_maps.visibility</code>. Determines if the map is visible to the Germinate interface or hidden.
     */
    public Boolean getVisibility() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>germinate_template_3_7_0.view_table_maps.visibility</code>. Determines if the map is visible to the Germinate interface or hidden.
     */
    public void setVisibility(Boolean value) {
        set(4, value);
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>germinate_template_3_7_0.view_table_maps.marker_count</code>.
     */
    public Long getMarkerCount() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>germinate_template_3_7_0.view_table_maps.marker_count</code>.
     */
    public void setMarkerCount(Long value) {
        set(5, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, Integer, Boolean, Long> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, Integer, Boolean, Long> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return ViewTableMaps.VIEW_TABLE_MAPS.MAP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ViewTableMaps.VIEW_TABLE_MAPS.MAP_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return ViewTableMaps.VIEW_TABLE_MAPS.MAP_DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return ViewTableMaps.VIEW_TABLE_MAPS.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field5() {
        return ViewTableMaps.VIEW_TABLE_MAPS.VISIBILITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return ViewTableMaps.VIEW_TABLE_MAPS.MARKER_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getMapId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getMapName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getMapDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component5() {
        return getVisibility();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component6() {
        return getMarkerCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getMapId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getMapName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getMapDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value5() {
        return getVisibility();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getMarkerCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewTableMapsRecord value1(Integer value) {
        setMapId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewTableMapsRecord value2(String value) {
        setMapName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewTableMapsRecord value3(String value) {
        setMapDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewTableMapsRecord value4(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewTableMapsRecord value5(Boolean value) {
        setVisibility(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewTableMapsRecord value6(Long value) {
        setMarkerCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewTableMapsRecord values(Integer value1, String value2, String value3, Integer value4, Boolean value5, Long value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }
// @formatter:on
}
