/*
 * This file is generated by jOOQ.
 */
package jhi.germinate.server.database.tables.records;


import javax.annotation.Generated;

import jhi.germinate.server.database.tables.ViewTableLicenses;

import org.jooq.Field;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.TableRecordImpl;


// @formatter:off
/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewTableLicensesRecord extends TableRecordImpl<ViewTableLicensesRecord> implements Record6<Integer, String, String, String, String, String> {

    private static final long serialVersionUID = -1816829304;

    /**
     * Setter for <code>germinate_template_3_7_0.view_table_licenses.licenseId</code>.
     */
    public void setLicenseid(Integer value) {
        set(0, value);
    }

    /**
     * Create a detached ViewTableLicensesRecord
     */
    public ViewTableLicensesRecord() {
        super(ViewTableLicenses.VIEW_TABLE_LICENSES);
    }

    /**
     * Setter for <code>germinate_template_3_7_0.view_table_licenses.licenseName</code>.
     */
    public void setLicensename(String value) {
        set(1, value);
    }

    /**
     * Create a detached, initialised ViewTableLicensesRecord
     */
    public ViewTableLicensesRecord(Integer licenseid, String licensename, String licensedescription, String licensecontent, String localename, String localedescription) {
        super(ViewTableLicenses.VIEW_TABLE_LICENSES);

        set(0, licenseid);
        set(1, licensename);
        set(2, licensedescription);
        set(3, licensecontent);
        set(4, localename);
        set(5, localedescription);
    }

    /**
     * Setter for <code>germinate_template_3_7_0.view_table_licenses.licenseDescription</code>.
     */
    public void setLicensedescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>germinate_template_3_7_0.view_table_licenses.licenseId</code>.
     */
    public Integer getLicenseid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>germinate_template_3_7_0.view_table_licenses.licenseContent</code>.
     */
    public void setLicensecontent(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>germinate_template_3_7_0.view_table_licenses.licenseName</code>.
     */
    public String getLicensename() {
        return (String) get(1);
    }

    /**
     * Setter for <code>germinate_template_3_7_0.view_table_licenses.localeName</code>.
     */
    public void setLocalename(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>germinate_template_3_7_0.view_table_licenses.licenseDescription</code>.
     */
    public String getLicensedescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>germinate_template_3_7_0.view_table_licenses.localeDescription</code>.
     */
    public void setLocaledescription(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>germinate_template_3_7_0.view_table_licenses.licenseContent</code>.
     */
    public String getLicensecontent() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, String, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, String, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return ViewTableLicenses.VIEW_TABLE_LICENSES.LICENSEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ViewTableLicenses.VIEW_TABLE_LICENSES.LICENSENAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return ViewTableLicenses.VIEW_TABLE_LICENSES.LICENSEDESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return ViewTableLicenses.VIEW_TABLE_LICENSES.LICENSECONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return ViewTableLicenses.VIEW_TABLE_LICENSES.LOCALENAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return ViewTableLicenses.VIEW_TABLE_LICENSES.LOCALEDESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getLicenseid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getLicensename();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getLicensedescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getLicensecontent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getLocalename();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getLocaledescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getLicenseid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getLicensename();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getLicensedescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getLicensecontent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getLocalename();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getLocaledescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewTableLicensesRecord value1(Integer value) {
        setLicenseid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewTableLicensesRecord value2(String value) {
        setLicensename(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewTableLicensesRecord value3(String value) {
        setLicensedescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewTableLicensesRecord value4(String value) {
        setLicensecontent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewTableLicensesRecord value5(String value) {
        setLocalename(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewTableLicensesRecord value6(String value) {
        setLocaledescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewTableLicensesRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>germinate_template_3_7_0.view_table_licenses.localeName</code>.
     */
    public String getLocalename() {
        return (String) get(4);
    }

    /**
     * Getter for <code>germinate_template_3_7_0.view_table_licenses.localeDescription</code>.
     */
    public String getLocaledescription() {
        return (String) get(5);
    }
// @formatter:on
}
