/*
 * This file is generated by jOOQ.
 */
package jhi.germinate.server.database.tables;


import org.jooq.*;
import org.jooq.impl.*;

import java.sql.Timestamp;
import java.util.*;

import javax.annotation.Generated;

import jhi.germinate.server.database.GerminateTemplate_3_7_0;
import jhi.germinate.server.database.tables.records.ExperimenttypesRecord;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Experimenttypes extends TableImpl<ExperimenttypesRecord> {

    private static final long serialVersionUID = -1681503448;

    /**
     * The reference instance of <code>germinate_template_3_7_0.experimenttypes</code>
     */
    public static final Experimenttypes EXPERIMENTTYPES = new Experimenttypes();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ExperimenttypesRecord> getRecordType() {
        return ExperimenttypesRecord.class;
    }

    /**
     * The column <code>germinate_template_3_7_0.experimenttypes.id</code>. Primary id for this table. This uniquely identifies the row.
     */
    public final TableField<ExperimenttypesRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "Primary id for this table. This uniquely identifies the row.");

    /**
     * The column <code>germinate_template_3_7_0.experimenttypes.description</code>. Describes the experiment type.
     */
    public final TableField<ExperimenttypesRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR(255), this, "Describes the experiment type.");

    /**
     * The column <code>germinate_template_3_7_0.experimenttypes.created_on</code>. When the record was created.
     */
    public final TableField<ExperimenttypesRecord, Timestamp> CREATED_ON = createField("created_on", org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "When the record was created.");

    /**
     * The column <code>germinate_template_3_7_0.experimenttypes.updated_on</code>. When the record was updated. This may be different from the created on date if subsequent changes have been made to the underlying record.
     */
    public final TableField<ExperimenttypesRecord, Timestamp> UPDATED_ON = createField("updated_on", org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "When the record was updated. This may be different from the created on date if subsequent changes have been made to the underlying record.");

    /**
     * Create a <code>germinate_template_3_7_0.experimenttypes</code> table reference
     */
    public Experimenttypes() {
        this(DSL.name("experimenttypes"), null);
    }

    /**
     * Create an aliased <code>germinate_template_3_7_0.experimenttypes</code> table reference
     */
    public Experimenttypes(String alias) {
        this(DSL.name(alias), EXPERIMENTTYPES);
    }

    /**
     * Create an aliased <code>germinate_template_3_7_0.experimenttypes</code> table reference
     */
    public Experimenttypes(Name alias) {
        this(alias, EXPERIMENTTYPES);
    }

    private Experimenttypes(Name alias, Table<ExperimenttypesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Experimenttypes(Name alias, Table<ExperimenttypesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return GerminateTemplate_3_7_0.GERMINATE_TEMPLATE_3_7_0;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ExperimenttypesRecord, Integer> getIdentity() {
        return Internal.createIdentity(jhi.germinate.server.database.tables.Experimenttypes.EXPERIMENTTYPES, jhi.germinate.server.database.tables.Experimenttypes.EXPERIMENTTYPES.ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ExperimenttypesRecord> getPrimaryKey() {
        return Internal.createUniqueKey(jhi.germinate.server.database.tables.Experimenttypes.EXPERIMENTTYPES, "KEY_experimenttypes_PRIMARY", jhi.germinate.server.database.tables.Experimenttypes.EXPERIMENTTYPES.ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ExperimenttypesRecord>> getKeys() {
        return Arrays.<UniqueKey<ExperimenttypesRecord>>asList(
              Internal.createUniqueKey(jhi.germinate.server.database.tables.Experimenttypes.EXPERIMENTTYPES, "KEY_experimenttypes_PRIMARY", jhi.germinate.server.database.tables.Experimenttypes.EXPERIMENTTYPES.ID)
        );
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Experimenttypes as(String alias) {
        return new Experimenttypes(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Experimenttypes as(Name alias) {
        return new Experimenttypes(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Experimenttypes rename(String name) {
        return new Experimenttypes(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Experimenttypes rename(Name name) {
        return new Experimenttypes(name, null);
    }
// @formatter:on
}
