/*
 * This file is generated by jOOQ.
 */
package jhi.germinate.server.database.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * Climate overlays can be used in conjunction with OpenStreetMap in order 
 * to visualize climate data in a geographic context.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Climateoverlays implements Serializable {

    private static final long serialVersionUID = 1241205406;

    private Integer   id;
    private Integer   climateId;
    private String    path;
    private Double    bottomLeftLongitude;
    private Double    bottomLeftLatitude;
    private Double    topRightLongitude;
    private Double    topRightLatitude;
    private Byte      isLegend;
    private String    description;
    private Timestamp createdOn;
    private Timestamp updatedOn;

    public Climateoverlays() {}

    public Climateoverlays(Climateoverlays value) {
        this.id = value.id;
        this.climateId = value.climateId;
        this.path = value.path;
        this.bottomLeftLongitude = value.bottomLeftLongitude;
        this.bottomLeftLatitude = value.bottomLeftLatitude;
        this.topRightLongitude = value.topRightLongitude;
        this.topRightLatitude = value.topRightLatitude;
        this.isLegend = value.isLegend;
        this.description = value.description;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
    }

    public Climateoverlays(
        Integer   id,
        Integer   climateId,
        String    path,
        Double    bottomLeftLongitude,
        Double    bottomLeftLatitude,
        Double    topRightLongitude,
        Double    topRightLatitude,
        Byte      isLegend,
        String    description,
        Timestamp createdOn,
        Timestamp updatedOn
    ) {
        this.id = id;
        this.climateId = climateId;
        this.path = path;
        this.bottomLeftLongitude = bottomLeftLongitude;
        this.bottomLeftLatitude = bottomLeftLatitude;
        this.topRightLongitude = topRightLongitude;
        this.topRightLatitude = topRightLatitude;
        this.isLegend = isLegend;
        this.description = description;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getClimateId() {
        return this.climateId;
    }

    public void setClimateId(Integer climateId) {
        this.climateId = climateId;
    }

    public String getPath() {
        return this.path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public Double getBottomLeftLongitude() {
        return this.bottomLeftLongitude;
    }

    public void setBottomLeftLongitude(Double bottomLeftLongitude) {
        this.bottomLeftLongitude = bottomLeftLongitude;
    }

    public Double getBottomLeftLatitude() {
        return this.bottomLeftLatitude;
    }

    public void setBottomLeftLatitude(Double bottomLeftLatitude) {
        this.bottomLeftLatitude = bottomLeftLatitude;
    }

    public Double getTopRightLongitude() {
        return this.topRightLongitude;
    }

    public void setTopRightLongitude(Double topRightLongitude) {
        this.topRightLongitude = topRightLongitude;
    }

    public Double getTopRightLatitude() {
        return this.topRightLatitude;
    }

    public void setTopRightLatitude(Double topRightLatitude) {
        this.topRightLatitude = topRightLatitude;
    }

    public Byte getIsLegend() {
        return this.isLegend;
    }

    public void setIsLegend(Byte isLegend) {
        this.isLegend = isLegend;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Timestamp getCreatedOn() {
        return this.createdOn;
    }

    public void setCreatedOn(Timestamp createdOn) {
        this.createdOn = createdOn;
    }

    public Timestamp getUpdatedOn() {
        return this.updatedOn;
    }

    public void setUpdatedOn(Timestamp updatedOn) {
        this.updatedOn = updatedOn;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Climateoverlays (");

        sb.append(id);
        sb.append(", ").append(climateId);
        sb.append(", ").append(path);
        sb.append(", ").append(bottomLeftLongitude);
        sb.append(", ").append(bottomLeftLatitude);
        sb.append(", ").append(topRightLongitude);
        sb.append(", ").append(topRightLatitude);
        sb.append(", ").append(isLegend);
        sb.append(", ").append(description);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);

        sb.append(")");
        return sb.toString();
    }
}
