/*
 * This file is generated by jOOQ.
 */
package jhi.germinate.server.database.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


// @formatter:off
/**
 * Describes mega environment data by grouping collection sites (locations) 
 * into mega environments. Mega environments in this context are collections 
 * of sites which meet the mega environment definition criteria.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Megaenvironmentdata implements Serializable {

    private static final long serialVersionUID = -919585237;

    private Integer   id;
    private Integer   locationId;
    private Integer   sourceId;
    private Integer   megaenvironmentId;
    private Boolean   isFinal;
    private Timestamp createdOn;
    private Timestamp updatedOn;

    public Megaenvironmentdata() {}

    public Megaenvironmentdata(Megaenvironmentdata value) {
        this.id = value.id;
        this.locationId = value.locationId;
        this.sourceId = value.sourceId;
        this.megaenvironmentId = value.megaenvironmentId;
        this.isFinal = value.isFinal;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
    }

    public Megaenvironmentdata(
        Integer   id,
        Integer   locationId,
        Integer   sourceId,
        Integer   megaenvironmentId,
        Boolean   isFinal,
        Timestamp createdOn,
        Timestamp updatedOn
    ) {
        this.id = id;
        this.locationId = locationId;
        this.sourceId = sourceId;
        this.megaenvironmentId = megaenvironmentId;
        this.isFinal = isFinal;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getLocationId() {
        return this.locationId;
    }

    public void setLocationId(Integer locationId) {
        this.locationId = locationId;
    }

    public Integer getSourceId() {
        return this.sourceId;
    }

    public void setSourceId(Integer sourceId) {
        this.sourceId = sourceId;
    }

    public Integer getMegaenvironmentId() {
        return this.megaenvironmentId;
    }

    public void setMegaenvironmentId(Integer megaenvironmentId) {
        this.megaenvironmentId = megaenvironmentId;
    }

    public Boolean getIsFinal() {
        return this.isFinal;
    }

    public void setIsFinal(Boolean isFinal) {
        this.isFinal = isFinal;
    }

    public Timestamp getCreatedOn() {
        return this.createdOn;
    }

    public void setCreatedOn(Timestamp createdOn) {
        this.createdOn = createdOn;
    }

    public Timestamp getUpdatedOn() {
        return this.updatedOn;
    }

    public void setUpdatedOn(Timestamp updatedOn) {
        this.updatedOn = updatedOn;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Megaenvironmentdata (");

        sb.append(id);
        sb.append(", ").append(locationId);
        sb.append(", ").append(sourceId);
        sb.append(", ").append(megaenvironmentId);
        sb.append(", ").append(isFinal);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);

        sb.append(")");
        return sb.toString();
    }
// @formatter:on
}
