/*
 * This file is generated by jOOQ.
 */
package jhi.germinate.server.database.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * The species table holds information relating to the species that are deinfed 
 * within a particular Germinate instance including common names and ploidy 
 * levels.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Taxonomies implements Serializable {

    private static final long serialVersionUID = -1836902381;

    private Integer   id;
    private String    genus;
    private String    species;
    private String    subtaxa;
    private String    speciesAuthor;
    private String    subtaxaAuthor;
    private String    cropname;
    private Integer   ploidy;
    private Timestamp createdOn;
    private Timestamp updatedOn;

    public Taxonomies() {}

    public Taxonomies(Taxonomies value) {
        this.id = value.id;
        this.genus = value.genus;
        this.species = value.species;
        this.subtaxa = value.subtaxa;
        this.speciesAuthor = value.speciesAuthor;
        this.subtaxaAuthor = value.subtaxaAuthor;
        this.cropname = value.cropname;
        this.ploidy = value.ploidy;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
    }

    public Taxonomies(
        Integer   id,
        String    genus,
        String    species,
        String    subtaxa,
        String    speciesAuthor,
        String    subtaxaAuthor,
        String    cropname,
        Integer   ploidy,
        Timestamp createdOn,
        Timestamp updatedOn
    ) {
        this.id = id;
        this.genus = genus;
        this.species = species;
        this.subtaxa = subtaxa;
        this.speciesAuthor = speciesAuthor;
        this.subtaxaAuthor = subtaxaAuthor;
        this.cropname = cropname;
        this.ploidy = ploidy;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getGenus() {
        return this.genus;
    }

    public void setGenus(String genus) {
        this.genus = genus;
    }

    public String getSpecies() {
        return this.species;
    }

    public void setSpecies(String species) {
        this.species = species;
    }

    public String getSubtaxa() {
        return this.subtaxa;
    }

    public void setSubtaxa(String subtaxa) {
        this.subtaxa = subtaxa;
    }

    public String getSpeciesAuthor() {
        return this.speciesAuthor;
    }

    public void setSpeciesAuthor(String speciesAuthor) {
        this.speciesAuthor = speciesAuthor;
    }

    public String getSubtaxaAuthor() {
        return this.subtaxaAuthor;
    }

    public void setSubtaxaAuthor(String subtaxaAuthor) {
        this.subtaxaAuthor = subtaxaAuthor;
    }

    public String getCropname() {
        return this.cropname;
    }

    public void setCropname(String cropname) {
        this.cropname = cropname;
    }

    public Integer getPloidy() {
        return this.ploidy;
    }

    public void setPloidy(Integer ploidy) {
        this.ploidy = ploidy;
    }

    public Timestamp getCreatedOn() {
        return this.createdOn;
    }

    public void setCreatedOn(Timestamp createdOn) {
        this.createdOn = createdOn;
    }

    public Timestamp getUpdatedOn() {
        return this.updatedOn;
    }

    public void setUpdatedOn(Timestamp updatedOn) {
        this.updatedOn = updatedOn;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Taxonomies (");

        sb.append(id);
        sb.append(", ").append(genus);
        sb.append(", ").append(species);
        sb.append(", ").append(subtaxa);
        sb.append(", ").append(speciesAuthor);
        sb.append(", ").append(subtaxaAuthor);
        sb.append(", ").append(cropname);
        sb.append(", ").append(ploidy);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);

        sb.append(")");
        return sb.toString();
    }
}
