/*
 * This file is generated by jOOQ.
 */
package jhi.germinate.server.database.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;

import jhi.germinate.server.database.enums.ViewTableDatasetAttributesAttributeType;


// @formatter:off
/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewTableDatasetAttributes implements Serializable {

    private static final long serialVersionUID = -1060511704;

    private Integer                                 datasetId;
    private String                                  datasetName;
    private String                                  datasetDescription;
    private Integer                                 attributeId;
    private String                                  attributeName;
    private String                                  attributeDescription;
    private ViewTableDatasetAttributesAttributeType attributeType;
    private String                                  targetTable;
    private Integer                                 foreignId;
    private String                                  attributeValue;

    public ViewTableDatasetAttributes() {}

    public ViewTableDatasetAttributes(ViewTableDatasetAttributes value) {
        this.datasetId = value.datasetId;
        this.datasetName = value.datasetName;
        this.datasetDescription = value.datasetDescription;
        this.attributeId = value.attributeId;
        this.attributeName = value.attributeName;
        this.attributeDescription = value.attributeDescription;
        this.attributeType = value.attributeType;
        this.targetTable = value.targetTable;
        this.foreignId = value.foreignId;
        this.attributeValue = value.attributeValue;
    }

    public ViewTableDatasetAttributes(
        Integer                                 datasetId,
        String                                  datasetName,
        String                                  datasetDescription,
        Integer                                 attributeId,
        String                                  attributeName,
        String                                  attributeDescription,
        ViewTableDatasetAttributesAttributeType attributeType,
        String                                  targetTable,
        Integer                                 foreignId,
        String                                  attributeValue
    ) {
        this.datasetId = datasetId;
        this.datasetName = datasetName;
        this.datasetDescription = datasetDescription;
        this.attributeId = attributeId;
        this.attributeName = attributeName;
        this.attributeDescription = attributeDescription;
        this.attributeType = attributeType;
        this.targetTable = targetTable;
        this.foreignId = foreignId;
        this.attributeValue = attributeValue;
    }

    public Integer getDatasetId() {
        return this.datasetId;
    }

    public void setDatasetId(Integer datasetId) {
        this.datasetId = datasetId;
    }

    public String getDatasetName() {
        return this.datasetName;
    }

    public void setDatasetName(String datasetName) {
        this.datasetName = datasetName;
    }

    public String getDatasetDescription() {
        return this.datasetDescription;
    }

    public void setDatasetDescription(String datasetDescription) {
        this.datasetDescription = datasetDescription;
    }

    public Integer getAttributeId() {
        return this.attributeId;
    }

    public void setAttributeId(Integer attributeId) {
        this.attributeId = attributeId;
    }

    public String getAttributeName() {
        return this.attributeName;
    }

    public void setAttributeName(String attributeName) {
        this.attributeName = attributeName;
    }

    public String getAttributeDescription() {
        return this.attributeDescription;
    }

    public void setAttributeDescription(String attributeDescription) {
        this.attributeDescription = attributeDescription;
    }

    public ViewTableDatasetAttributesAttributeType getAttributeType() {
        return this.attributeType;
    }

    public void setAttributeType(ViewTableDatasetAttributesAttributeType attributeType) {
        this.attributeType = attributeType;
    }

    public String getTargetTable() {
        return this.targetTable;
    }

    public void setTargetTable(String targetTable) {
        this.targetTable = targetTable;
    }

    public Integer getForeignId() {
        return this.foreignId;
    }

    public void setForeignId(Integer foreignId) {
        this.foreignId = foreignId;
    }

    public String getAttributeValue() {
        return this.attributeValue;
    }

    public void setAttributeValue(String attributeValue) {
        this.attributeValue = attributeValue;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ViewTableDatasetAttributes (");

        sb.append(datasetId);
        sb.append(", ").append(datasetName);
        sb.append(", ").append(datasetDescription);
        sb.append(", ").append(attributeId);
        sb.append(", ").append(attributeName);
        sb.append(", ").append(attributeDescription);
        sb.append(", ").append(attributeType);
        sb.append(", ").append(targetTable);
        sb.append(", ").append(foreignId);
        sb.append(", ").append(attributeValue);

        sb.append(")");
        return sb.toString();
    }
// @formatter:on
}
