/*
 * This file is generated by jOOQ.
 */
package jhi.germinate.server.database.tables;


import com.google.gson.JsonArray;

import javax.annotation.Generated;

import jhi.germinate.server.database.GerminateTemplate_4_0_0;
import jhi.germinate.server.database.tables.records.ViewTableGroupMarkersRecord;
import jhi.germinate.server.util.SynonymBinding;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


// @formatter:off
/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewTableGroupMarkers extends TableImpl<ViewTableGroupMarkersRecord> {

    private static final long serialVersionUID = -825189728;

    /**
     * The reference instance of <code>germinate_template_4_0_0.view_table_group_markers</code>
     */
    public static final ViewTableGroupMarkers VIEW_TABLE_GROUP_MARKERS = new ViewTableGroupMarkers();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ViewTableGroupMarkersRecord> getRecordType() {
        return ViewTableGroupMarkersRecord.class;
    }

    /**
     * The column <code>germinate_template_4_0_0.view_table_group_markers.marker_id</code>. Primary id for this table. This uniquely identifies the row.
     */
    public final TableField<ViewTableGroupMarkersRecord, Integer> MARKER_ID = createField("marker_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "Primary id for this table. This uniquely identifies the row.");

    /**
     * The column <code>germinate_template_4_0_0.view_table_group_markers.marker_name</code>. The name of the marker. This should be a unique name which identifies the marker.
     */
    public final TableField<ViewTableGroupMarkersRecord, String> MARKER_NAME = createField("marker_name", org.jooq.impl.SQLDataType.VARCHAR(45).nullable(false), this, "The name of the marker. This should be a unique name which identifies the marker.");

    /**
     * The column <code>germinate_template_4_0_0.view_table_group_markers.marker_type</code>. Describes the marker type. Markers (markers) have a defined type. This could be AFLP, MicroSat, SNP and so on.
     */
    public final TableField<ViewTableGroupMarkersRecord, String> MARKER_TYPE = createField("marker_type", org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "Describes the marker type. Markers (markers) have a defined type. This could be AFLP, MicroSat, SNP and so on.");

    /**
     * The column <code>germinate_template_4_0_0.view_table_group_markers.marker_synonyms</code>. The synonyms as a json array.
     */
    public final TableField<ViewTableGroupMarkersRecord, JsonArray> MARKER_SYNONYMS = createField("marker_synonyms", org.jooq.impl.DefaultDataType.getDefaultDataType("\"germinate_template_4_0_0\".\"view_table_group_markers_marker_synonyms\""), this, "The synonyms as a json array.", new SynonymBinding());

    /**
     * The column <code>germinate_template_4_0_0.view_table_group_markers.group_id</code>. Foreign key to groups (groups.id).
     */
    public final TableField<ViewTableGroupMarkersRecord, Integer> GROUP_ID = createField("group_id", org.jooq.impl.SQLDataType.INTEGER, this, "Foreign key to groups (groups.id).");

    /**
     * Create a <code>germinate_template_4_0_0.view_table_group_markers</code> table reference
     */
    public ViewTableGroupMarkers() {
        this(DSL.name("view_table_group_markers"), null);
    }

    /**
     * Create an aliased <code>germinate_template_4_0_0.view_table_group_markers</code> table reference
     */
    public ViewTableGroupMarkers(String alias) {
        this(DSL.name(alias), VIEW_TABLE_GROUP_MARKERS);
    }

    /**
     * Create an aliased <code>germinate_template_4_0_0.view_table_group_markers</code> table reference
     */
    public ViewTableGroupMarkers(Name alias) {
        this(alias, VIEW_TABLE_GROUP_MARKERS);
    }

    private ViewTableGroupMarkers(Name alias, Table<ViewTableGroupMarkersRecord> aliased) {
        this(alias, aliased, null);
    }

    private ViewTableGroupMarkers(Name alias, Table<ViewTableGroupMarkersRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("VIEW"));
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return GerminateTemplate_4_0_0.GERMINATE_TEMPLATE_4_0_0;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewTableGroupMarkers as(String alias) {
        return new ViewTableGroupMarkers(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewTableGroupMarkers as(Name alias) {
        return new ViewTableGroupMarkers(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ViewTableGroupMarkers rename(String name) {
        return new ViewTableGroupMarkers(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ViewTableGroupMarkers rename(Name name) {
        return new ViewTableGroupMarkers(name, null);
    }
// @formatter:on
}
