package jhi.germinate.resource.enums;

public enum ImportStatus
{
	OK,
	GENERIC_IO_ERROR,
	GENERIC_MISSING_EXCEL_SHEET,
	GENERIC_MISSING_COLUMN,
	MCPD_DUPLICATE_ACCENUMB,
	MCPD_INVALID_COUNTRY_CODE,
	MCPD_INVALID_DATE,
	MCPD_MISSING_FIELD,
	MCPD_INVALID_SAMPSTAT,
	MCPD_INVALID_COLLSRC,
	MCPD_INVALID_STORAGE,
	MCPD_INVALID_NUMBER,
	MCPD_INVALID_ENTITY_TYPE,
	MCPD_INVALID_ENTITY_PARENT_ACCENUMB
}