/*
 * This file is generated by jOOQ.
 */
package jhi.germinate.server.database.routines;


import javax.annotation.Generated;

import jhi.germinate.server.database.GerminateTemplate_4_0_0;

import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DatasetMeta extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = -686042381;

    /**
     * Create a new routine call instance
     */
    public DatasetMeta() {
        super("dataset_meta", GerminateTemplate_4_0_0.GERMINATE_TEMPLATE_4_0_0);
    }
}
